Repository Thigzz/Group-8-Beauty-Shop, pull requests merged in 2025-09, with the labels that each got.

#60 Feature/backend models
  .gitignore
  server/app.py
  server/app/__init__.py
  server/app/__pycache__/app.cpython-312.pyc
  server/app/config.py
  server/app/extensions.py
  server/app/models/__init__.py
  server/app/models/address.py
  server/app/models/base.py
  server/app/models/cart_items.py
  server/app/models/carts.py
  server/app/models/category.py
  server/app/models/enums.py
  server/app/models/invoice.py
  server/app/models/order_items.py
  server/app/models/orders.py
  server/app/models/password_reset_audit.py
  server/app/models/payment.py
  server/app/models/product.py
  server/app/models/security_question.py
  server/app/models/sub_category.py
  server/app/models/user_security_audit.py
  server/app/models/user_security_questions.py
  server/app/models/users.py
  server/app/seed.py
  server/migrations/README
  server/migrations/alembic.ini
  server/migrations/env.py
  server/migrations/script.py.mako
  server/requirements.txt
Labels: Backend

#66 Feature/api security products checkout
  server/app/__init__.py
  server/app/routes/__init__.py
  server/app/routes/admin_reset_password.py
  server/app/routes/categories.py
  server/app/routes/checkout.py
  server/app/routes/orders.py
  server/app/routes/products.py
  server/app/routes/security_questions.py
Labels: Backend

#61 31 admin activatedeactivate user api
  Pipfile
  client/src/App.jsx
  client/src/main.jsx
  pytest.ini
  requirements.txt
  server/Pipfile
  server/__init__.py
  server/app.py
  server/app/__init__.py
  server/app/models/address.py
  server/app/models/base.py
  server/app/models/cart_items.py
  server/app/models/carts.py
  server/app/models/invoice.py
  server/app/models/order_items.py
  server/app/models/orders.py
  server/app/models/password_reset_audit.py
  server/app/models/payment.py
  server/app/models/product.py
  server/app/models/security_question.py
  server/app/models/sub_category.py
  server/app/models/user_security_audit.py
  server/app/models/user_security_questions.py
  server/app/models/users.py
  server/app/routes/__init__.py
  server/app/routes/admin.py
  server/app/seed.py
  server/migrations/env.py
  server/tests/conftest.py
  server/tests/test_admin_endpoints.py
Labels: Backend

#62 34 cart api
  server/app/models/carts.py
  server/app/routes/auth.py
  server/app/routes/cart.py
  server/app/seed.py
  server/app/utils/cart_utils.py
  server/migrations/env.py
  server/tests/test_cart_full.py
  server/tests/test_cart_merge.py
Labels: Backend

#63 37 order fulfillment api
  server/app/routes/orders.py
  server/tests/test_orders.py
Labels: Backend

#76 Feat: Add Sub Category, Analytics and Reporting Modules
  server/Routes.md
  server/app/__init__.py
  server/app/models/address.py
  server/app/models/orders.py
  server/app/models/users.py
  server/app/routes/addresses.py
  server/app/routes/admin.py
  server/app/routes/analytics.py
  server/app/routes/auth.py
  server/app/routes/cart.py
  server/app/routes/reports.py
  server/app/routes/sub_categories.py
  server/app/seed.py
  server/instance/beauty_shop.db:Zone.Identifier
  server/migrations/versions/e94a1f54b8aa_initial_database_migration.py
  server/tests/test_admin_endpoints.py
  server/tests/test_analytics.py
  server/tests/test_auth.py
  server/tests/test_cart_full.py
  server/tests/test_cart_merge.py
  server/tests/test_categories.py
  server/tests/test_orders.py
  server/tests/test_products.py
  server/tests/test_sub_categories.py
  server/tests/test_user_profile_and_address.py
Labels: Backend

#77 Hotfix/Deployment Migrations and Admin Seeding
  .gitignore
  Pipfile
  build.sh
  client/src/App.jsx
  client/src/main.jsx
  server/Pipfile
  server/app.py
  server/app/__pycache__/app.cpython-312.pyc
  server/app/models/base.py
  server/app/seed.py
  server/migrations/versions/94476ed68a66_automated_migration.py
  server/migrations/versions/e94a1f54b8aa_initial_database_migration.py
  server/requirements.txt
Labels: Backend

#96 feat:added admin reports andd orders page
  client/src/pages/AdminOrdersPage.jsx
  client/src/pages/AdminReportsPage.jsx
Labels: FrontEnd

#110 51 admin products page
  client/public/sample-products.csv
  client/src/App.jsx
  client/src/api/axios.js
  client/src/components/AddressForm.jsx
  client/src/components/Breadcrumb.jsx
  client/src/components/CategoryPageWrapper.jsx
  client/src/components/CategoryProvider.jsx
  client/src/components/admin/ConfirmationModal.jsx
  client/src/pages/AdminOrdersPage.jsx
  client/src/pages/AdminReportsPage.jsx
  client/src/pages/CategoryPage.jsx
  client/src/pages/admin/AddProductPage.jsx
  client/src/pages/admin/AdminOrderDetails.jsx
  client/src/pages/admin/EditProductPage.jsx
  client/src/pages/admin/ProductsPage.jsx
  client/src/redux/features/admin/adminSlice.js
  client/src/redux/features/categories/categoriesSlice.js
  client/src/redux/features/orders/orderSlice.js
  client/src/redux/features/products/productsSlice.js
  client/src/redux/features/profile/profileSlice.js
  client/src/redux/store.js
  client/tests/components/admin/AddProductpage.test.jsx
  client/tests/components/admin/EditProduct.test.jsx
  client/tests/components/admin/ProductsPage.test.jsx
  server/app/models/order_items.py
  server/app/models/orders.py
  server/app/models/product.py
  server/app/routes/orders.py
  server/app/routes/products.py
  server/migrations/versions/acec9e1d0922_add_status_to_product.py
  server/migrations/versions/baf111a3b4b8_change_status_column_to_boolean.py
  server/tests/test_products.py
Labels: Backend, FrontEnd
